### ISSUE TITLE
Recreate this using ReactJS library for building user interfaces or UI components.

### ISSUE THREAD

**Issue by iamayushdas** [iamayushdas/cart#2]
### Subject of the issue
recreate tis merchandise form to react framework

### Steps to reproduce
1. Git clone the following repository as this will be the standard website we will convert to React
Create a new React Application running the following commands in your Terminal or Console:
npx create-react-app my-reactapp
cd my-reactapp
npm start

2. Replace my-reactapp with an app name of your choosing. Once you have run the above command, your server should be running and fire up a webpage with a spinning React Logo and a background. All of your resources will be located in the my-reactapp/public folder.

3. Move all of the folders (css/, fonts/, img/, js/) from your Creative Template to your React Project’s public folder. You will need to add these references to the public/index.html file in your React Application.

**Comment by esau-morais** [comment]
Please describe better the issue to improve my solution

**Comment by esau-morais** [comment]
Thank your for request this issue! I can get this.

_Just remember: React.js is not a framework_

**Comment by esau-morais** [comment]
_Note: Please, assign me to this issue to prevent spam and close the issue_

**Comment by iamayushdas** [comment]
> Note: Please, assign me to this issue to prevent spam and close it

### Done
